@startmindmap "Проверочный лист"
* Безопасность данных
** Публичные данные
*** Адреса и время работы офисов продаж
**** Риск: Искажение
***** Влияние: Незначительный
*** Список жилых комплексов
**** Риск: Искажение
***** Влияние: Незначительный
*** Доступные к покупке объекты недвижимости
**** Риск: Искажение
***** Влияние: Незначительный
*** Стоимость объектов
**** Риск: Искажение
***** Влияние: Незначительный
*** Наличие текущей брони
**** Риск: Искажение
***** Влияние: Незначительный

** Внутренние данные
*** Данные о работе внутренних систем
**** Риск: Утечка
***** Влияние: Незначительный
**** Риск: Потеря
***** Влияние: Значительный
**** Риск: Искажение
***** Влияние: Значительный
*** Внутренние инструкции для менеджеров по продажам
**** Риск: Искажение
***** Влияние: Значительный
*** Отчеты о капитальном ремонте
**** Риск: Искажение
***** Влияние: Значительный

** Конфиденциальные данные
*** Персональные данные клиентов
**** Риск: Утечка
***** Влияние: Значительный
*** Персональные данные собственников
**** Риск: Утечка
***** Влияние: Значительный
*** Максимальный размер дисконта на объект
**** Риск: Обесценивание
***** Влияние: Значительный
*** Тарифы ЖКХ конкретной управляющей компании
**** Риск: Обесценивание
***** Влияние: Значительный
*** Стоимость проведенных сделок
**** Риск: Обесценивание
***** Влияние: Значительный
*** Факты и стоимость бронирований
**** Риск: Обесценивание
***** Влияние: Значительный

** Секретные данные
*** Платежные данные клиентов и собственников
**** Риск: Утечка
***** Влияние: Критический
**** Риск: Искажение
***** Влияние: Критический
*** Данные для регистрации в Росреестре
**** Риск: Утечка
***** Влияние: Критический
*** Данные по настройкам систем безопасности, управления освещением и другими функциями
**** Риск: Утечка
***** Влияние: Критический
*** Соглашения о неразглашении NDA
**** Риск: Утечка
***** Влияние: Критический
@endmindmap
